image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9

services:
  - docker:dind

stages:
  - build
  - test
  - push

before_script:
  - apk add docker
  - docker --version

build_job:
  stage: build
  when: always
  script:
    - dotnet restore
    - dotnet publish -c Release

test_job:
  stage: test
  when: always
  script:
    - dotnet test

push_job:
  stage: push
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker-compose build
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest