image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9

services:
  - docker:dind

stages:
  - build
  - test
  - push

cache:
  paths:
    - TechCalendar.Web/bin/Release/

build_job:
  stage: build
  when: always
  script:
    - dotnet restore
    - dotnet publish -c Release

test_job:
  stage: test
  when: always
  script:
    - dotnet test

push_job:
  stage: push
  only:
    - master
  before_script:
    - apk add docker
    - docker --version
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker-compose build
    - docker push registry.gitlab.com/kuper-adrian/stream-schedule.io/nginx:latest
    - docker push registry.gitlab.com/kuper-adrian/stream-schedule.io/web:latest