version: '3.4'

services:

  api:
    volumes:
      - ./TechCalendar.Api/Data/:/app/Data/

  nginx:
    volumes:
      - ./nginx/dev-certs/:/etc/letsencrypt/live/stream-schedule.io/
    ports:
      - 50080:80
      - 50443:443
