version: '3.4'

services:
  
  web:
    restart: always
    image: stream-schedule-web:latest
    build:
      context: .
      dockerfile: TechCalendar.Web/Dockerfile
    container_name: stream-schedule-web
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: http://+:6000
  
  nginx:
    restart: always
    image: stream-schedule-nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: stream-schedule-nginx
